const items = [
  new Item({ id: 10, takeable: true, name: "KEY", showname: "a KEY" }),
  new Item({ id: 11, takeable: true, name: "AXE", showname: "an AXE" }),
  new Item({ id: 12, takeable: true, name: "STICKS", showname: "STICKS" }),
  new Item({
    id: 13,
    takeable: false,
    name: "SHEEPLEGS",
    showname: "sheeplegs",
  }),
  new Item({
    id: 14,
    takeable: true,
    name: "MUSHROOMS",
    showname: "MUSHROOMS",
  }),
  new Item({ id: 15, takeable: true, name: "MONEY", showname: "MONEY" }),
  new Item({ id: 16, takeable: true, name: "BARREL", showname: "a BARREL" }),
  new Item({
    id: 17,
    takeable: false,
    name: "SHEEPTRUNK",
    showname: "a sheeptrunk",
  }),
  new Item({ id: 18, takeable: true, name: "BERRIES", showname: "BERRIES" }),
  new Item({ id: 19, takeable: true, name: "WOOL", showname: "WOOL" }),
  new Item({
    id: 20,
    takeable: false,
    name: "SHEEPSKIN",
    showname: "a sheepskin",
  }),
  new Item({ id: 21, takeable: true, name: "BAG", showname: "a BAG" }),
  new Item({ id: 22, takeable: true, name: "RAG", showname: "a RAG" }),
  new Item({
    id: 23,
    takeable: false,
    name: "SHEEPHEAD",
    showname: "a sheephead",
  }),
  new Item({ id: 24, takeable: true, name: "SPADE", showname: "a SPADE" }),
  new Item({ id: 25, takeable: true, name: "SULPHUR", showname: "SULPHUR" }),
  new Item({
    id: 26,
    takeable: false,
    name: "SOLID POISON",
    showname: "a solid poison",
  }),
  new Item({ id: 27, takeable: true, name: "BUCKET", showname: "a BUCKET" }),
  new Item({ id: 28, takeable: true, name: "TAR", showname: "TAR" }),
  new Item({
    id: 29,
    takeable: false,
    name: "LIQUID POISON",
    showname: "a liquid poison",
  }),
  new Item({
    id: 30,
    takeable: false,
    name: "DEAD DRAGON",
    showname: "a dead dragon",
  }),
  new Item({ id: 31, takeable: true, name: "STONE", showname: "a STONE" }),
  new Item({ id: 32, takeable: true, name: "FISH", showname: "a FISH" }),
  new Item({ id: 33, takeable: true, name: "KNIFE", showname: "a KNIFE" }),
  new Item({
    id: 34,
    takeable: true,
    name: "DRAGONSKIN",
    showname: "a DRAGONSKIN",
  }),
  new Item({
    id: 35,
    takeable: true,
    name: "SHOES",
    showname: "a dragonskin SHOES",
  }),
  new Item({ id: 36, takeable: true, name: "PRIZE", showname: "a PRIZE" }),
  new Item({ id: 37, takeable: true, name: "SHEEP", showname: "a SHEEP" }),
];

const locations = [
  new Location({
    id: 11,
    description: "You are inside a brimstone mine",
    image: "./img/11.gif",
    color: "rgb(235, 211, 64)",
    directions: {
      EAST: 12,
    },
    items: [],

    // if (this.currentLocation.trade[this.inHand.id])
    trade: [
      {
        message: [
          "You are digging...",
          "and digging...",
          "That's enough sulphur for you",
        ],
        from: 24,
        to: 25,
      },
    ],
  }),
  new Location({
    id: 12,
    description: "You are at the entrance to the mine",
    image: "./img/12.gif",
    color: "rgb(89, 93, 87)",
    directions: {
      WEST: 11,
      EAST: 13,
    },
    items: [],
    trade: [],
  }),
  new Location({
    id: 13,
    description: "A hill",
    image: "./img/13.gif",
    color: "rgb(117, 237, 243)",
    directions: {
      EAST: 14,
      WEST: 12,
      SOUTH: 23,
    },
    items: [31],
    trade: [],
  }),
  new Location({
    id: 14,
    description: "Some bushes",
    image: "./img/14.gif",
    color: "rgb(202, 230, 51)",
    directions: {
      EAST: 15,
      WEST: 13,
    },
    items: [],
    trade: [],
  }),
  new Location({
    id: 15,
    description: "An old deserted hut",
    image: "./img/15.gif",
    color: "rgb(220, 204, 61)",
    directions: {
      EAST: 16,
      WEST: 14,
    },
    items: [27],
    trade: [],
  }),
  new Location({
    id: 16,
    description: "The edge of a forest",
    image: "./img/16.gif",
    color: "rgb(167, 245, 63)",
    directions: {
      EAST: 17,
      WEST: 15,
    },
    items: [],
    trade: [],
  }),
  new Location({
    id: 17,
    description: "A dark forest",
    image: "./img/16.gif",
    color: "rgb(167, 245, 63)",
    directions: {
      SOUTH: 27,
      WEST: 16,
    },
    items: [14],
    trade: [],
  }),
  new Location({
    id: 21,
    description: "A man nearby making tar",
    image: "./img/21.gif",
    color: "rgb(255, 190, 99)",
    directions: {
      EAST: 22,
      SOUTH: 31,
    },
    items: [],
    trade: [
      {
        message: ["You got a bucket full of tar"],
        from: 27,
        to: 28,
      },
    ],
  }),
  new Location({
    id: 22,
    description: "A timber yard",
    image: "./img/22.gif",
    color: "rgb(255, 190, 99)",
    directions: {
      EAST: 23,
      WEST: 21,
      SOUTH: 32,
    },
    items: [],
    trade: [],
  }),
  new Location({
    id: 23,
    description: "You are by a roadside shrine",
    image: "./img/23.gif",
    color: "rgb(167, 245, 63)",
    directions: {
      EAST: 24,
      WEST: 22,
      SOUTH: 33,
      NORTH: 13,
    },
    items: [10],
    trade: [],
  }),
  new Location({
    id: 24,
    description: "You are by a small chapel",
    image: "./img/24.gif",
    color: "rgb(212, 229, 36)",
    directions: {
      EAST: 25,
      WEST: 23,
    },
    items: [],
    trade: [],
  }),
  new Location({
    id: 25,
    description: "You are on a road leading to a wood",
    image: "./img/25.gif",
    color: "rgb(167, 245, 63)",
    directions: {
      EAST: 26,
      WEST: 24,
      SOUTH: 35,
    },
    items: [],
    trade: [],
  }),
  new Location({
    id: 26,
    description: "You are in a forest",
    image: "./img/26.gif",
    color: "rgb(167, 245, 63)",
    directions: {
      EAST: 27,
      WEST: 25,
    },
    items: [],
    trade: [],
  }),
  new Location({
    id: 27,
    description: "You are in a deep forest",
    image: "./img/27.gif",
    color: "rgb(140, 253, 99)",
    directions: {
      NORTH: 17,
      WEST: 26,
    },
    items: [18],
    trade: [],
  }),
  new Location({
    id: 31,
    description: "You are by the Vistula River",
    image: "./img/31.gif",
    color: "rgb(122, 232, 252)",
    directions: {
      NORTH: 21,
      EAST: 32,
    },
    items: [],
    trade: [],
  }),
  new Location({
    id: 32,
    description: "You are by the Vistula River",
    image: "./img/32.gif",
    color: "rgb(140, 214, 255)",
    directions: {
      NORTH: 22,
      WEST: 31,
    },
    items: [32],
    trade: [],
  }),
  new Location({
    id: 33,
    description: "You are on a bridge over river",
    image: "./img/33.gif",
    color: "rgb(108, 181, 242)",
    directions: {
      NORTH: 23,
      SOUTH: 43,
    },
    items: [],
    trade: [],
  }),
  new Location({
    id: 34,
    description: "You are by the old tavern",
    image: "./img/34.gif",
    color: "rgb(255, 189, 117)",
    directions: {
      EAST: 35,
    },
    items: [],
    trade: [
      {
        message: ["The tavern owner paid you money"],
        from: 14,
        to: 15,
      },
    ],
  }),
  new Location({
    id: 35,
    description: "You are at the town's end",
    image: "./img/35.gif",
    color: "rgb(255, 190, 99)",
    directions: {
      NORTH: 25,
      SOUTH: 45,
      WEST: 34,
    },
    items: [],
    trade: [],
  }),
  new Location({
    id: 36,
    description: "You are in a butcher's shop",
    image: "./img/36.gif",
    color: "rgb(255, 188, 102)",
    directions: {
      SOUTH: 46,
    },
    items: [],
    trade: [
      {
        message: ["The butcher gave you wool"],
        from: 18,
        to: 19,
      },
    ],
  }),
  new Location({
    id: 37,
    description: "You are in a cooper's house",
    image: "./img/37.gif",
    color: "rgb(255, 188, 102)",
    directions: {
      SOUTH: 47,
    },
    items: [],
    trade: [
      {
        message: ["The cooper sold you a new barrel"],
        from: 15,
        to: 16,
      },
    ],
  }),
  new Location({
    id: 41,
    description: "You are in the Wawel Castle",
    image: "./img/41.gif",
    color: "rgb(255, 176, 141)",
    directions: {
      EAST: 42,
    },
    items: [],
    trade: [
      {
        message: ["The King is impressed by your shoes"],
        from: 35,
        to: 36,
      },
      {
        from: 36,
      },
    ],
  }),
  new Location({
    id: 42,
    description: "You are inside a dragon's cave",
    image: "./img/42.gif",
    color: "rgb(198, 205, 193)",
    directions: {
      WEST: 41,
      EAST: 43,
    },
    items: [],
    trade: [],
  }),
  new Location({
    id: 43,
    description: "A perfect place to set a trap",
    image: "./img/43.gif",
    color: "rgb(255, 176, 141)",
    dragonParts: true,
    directions: {
      WEST: 42,
      NORTH: 33,
    },
    items: [],
    trade: [
      {
        message: ["You prepared legs for your fake sheep, OK"],
        from: 12,
        to: 13,
      },
      {
        message: ["You made a nice sheeptrunk, OK"],
        from: 16,
        to: 17,
      },
      {
        message: ["You prepared skin for your fake sheep, OK"],
        from: 19,
        to: 20,
      },
      {
        message: ["You made a fake sheephead, OK"],
        from: 22,
        to: 23,
      },
      {
        message: ["You prepared a solid poison, OK"],
        from: 25,
        to: 26,
      },
      {
        message: ["You prepared a liquid poison, OK"],
        from: 28,
        to: 29,
      },
      {
        message: [
          "Your fake sheep is full of poison and ready to be eaten by the dragon",
        ],
        to: 37,
      },
      {
        message: [
          "The dragon noticed your gift...",
          "The dragon ate your sheep and died!",
        ],
        from: 37,
        to: 30,
        image: "./img/death-dragon.bmp",
      },
      {
        message: ["You cut a piece of dragon's skin"],
        from: 33,
        to: 34,
      },
    ],
  }),
  new Location({
    id: 44,
    description: "You are by the water mill",
    image: "./img/44.gif",
    color: "rgb(255, 190, 99)",
    directions: {
      EAST: 45,
    },
    items: [21],
    trade: [],
  }),
  new Location({
    id: 45,
    description: "You are at a main crossroad",
    image: "./img/45.gif",
    color: "rgb(255, 190, 99)",
    directions: {
      NORTH: 35,
      SOUTH: 55,
      WEST: 44,
      EAST: 46,
    },
    items: [],
    trade: [],
  }),
  new Location({
    id: 46,
    description: "You are on a town street",
    image: "./img/46.gif",
    color: "rgb(255, 190, 99)",
    directions: {
      NORTH: 36,
      WEST: 45,
      EAST: 47,
    },
    items: [],
    trade: [],
  }),
  new Location({
    id: 47,
    description: "You are in a frontyard of your house",
    image: "./img/47.gif",
    color: "rgb(255, 190, 99)",
    directions: {
      NORTH: 37,
      SOUTH: 57,
      WEST: 46,
    },
    items: [],
    trade: [],
  }),

  new Location({
    id: 54,
    description: "You are by a swift stream",
    image: "./img/54.gif",
    color: "rgb(108, 181, 242)",
    directions: {
      EAST: 55,
    },
    items: [],
    trade: [],
  }),

  new Location({
    id: 55,
    description: "You are on a street leading forest",
    image: "./img/55.gif",
    color: "rgb(255, 190, 99)",
    directions: {
      WEST: 54,
      NORTH: 45,
      SOUTH: 65,
    },
    items: [33],
    trade: [],
  }),
  new Location({
    id: 56,
    description: "You are in a woodcutter's backyard",
    image: "./img/56.gif",
    color: "rgb(255, 190, 99)",
    directions: {
      SOUTH: 66,
    },
    items: [],
    trade: [
      {
        message: ["You opened a tool shed and took an axe"],
        from: 10,
        to: 11,
      },
    ],
  }),
  new Location({
    id: 57,
    description: "You are in a shoemaker's house",
    image: "./img/57.gif",
    color: "rgb(254, 194, 97)",
    directions: {
      NORTH: 47,
    },
    items: [],
    trade: [
      {
        message: ["You used your tools to make a rag"],
        from: 21,
        to: 22,
      },
      {
        message: ["You used your tools to make shoes"],
        from: 34,
        to: 35,
      },
    ],
  }),
  new Location({
    id: 64,
    description: "You are in a bleak funeral house",
    image: "./img/64.gif",
    color: "rgb(254, 194, 97)",
    directions: {
      EAST: 65,
    },
    items: [24],
    trade: [],
  }),
  new Location({
    id: 65,
    description: "You are on a path leading to the wood",
    image: "./img/65.gif",
    color: "rgb(167, 245, 63)",
    directions: {
      NORTH: 55,
      WEST: 64,
      EAST: 66,
    },
    items: [],
    trade: [],
  }),
  new Location({
    id: 66,
    description: "You are at the edge of a forest",
    image: "./img/66.gif",
    color: "rgb(167, 245, 63)",
    directions: {
      NORTH: 56,
      WEST: 65,
      EAST: 67,
    },
    items: [],
    trade: [],
  }),

  new Location({
    id: 67,
    description: "You are in a deep forest",
    image: "./img/67.gif",
    color: "rgb(140, 253, 99)",
    directions: {
      WEST: 66,
    },
    items: [],
    trade: [
      {
        message: ["You cut sticks for sheeplegs"],
        from: 11,
        to: 12,
      },
    ],
  }),
];
